---
- hosts: red
  remote_user: root
  tasks:
    # First and foremost, install nodejs!!
    - name: Install nodejs
      raw: curl -sL https://deb.nodesource.com/setup_5.x | bash
    - apt: name=nodejs state=present

    # Create /pentest dir
    - name: Create pentest directory
      raw: mkdir /pentest

    # Install apache for reverse proxying
    - apt: name=apache2 state=present
    - command: a2enmod proxy proxy_ajp proxy_http rewrite deflate headers proxy_balancer proxy_connect proxy_html

    # Install shellcreeper
    - name: Clone shellcreeper
      git: repo=https://github.com/gabemarshall/shellcreeper.git dest=/pentest/shellcreeper
    - name: Install shellcreeper
      raw: cd /pentest/shellcreeper && npm install

    # Install metasploit and empire dockerfiles
    - name: Clone Red2 dockerfiles
      git: repo=https://github.com/gabemarshall/redc2.git dest=/pentest/redc2
    - name: Build Red2 msf dockerfile
      raw: docker build -t msf /pentest/redc2/msf
    - name: Build Red2 empire dockerfile
      raw: docker build -t msf /pentest/redc2/msf

    - name: Clone dnscat2  
      git: repo=https://github.com/iagox86/dnscat2 dest=/pentest/dnscat2

    - name: Build dnscat2 docker container
      raw: docker build -t dnscat2 /pentest/dnscat2/server

    # Install Brosec
    - name: Download Brosec
      raw: wget https://github.com/gabemarshall/Brosec/releases/download/1.0/bros-1.0-linux-x86_64.tar.gz
    - name: Untar Brosec
      raw: tar xvf bros-1.0-linux-x86_64.tar.gz
    - name: Chmod
      raw: chmod +x bros-1.0-linux-x86_64
    - name: Move Brosec
      raw: mv bros-1.0-linux-x86_64 /usr/local/bin/bros

    - name: Change ssh port to 22222
      raw: sed -i -e 's/^Port .*/Port 22122/' /etc/ssh/sshd_config
    - name: Restart ssh server
      raw: service ssh restart
