FROM python:2
RUN apt-get install wget
RUN git clone https://github.com/upgoingstar/datasploit
WORKDIR /datasploit
RUN pip install -r requirements.txt
# docker run -it --rm recon-ng python enumall.py
